import { createTamagui, createTokens } from '@tamagui/core';
import { hexColors } from './hexColors';
import { typography, spacing, radius, media } from '../utils/responsive';

const tamaguiTokens = createTokens({
  color: {
    // Light theme colors
    lightPrimary: hexColors.light.primary,
    lightPrimaryLight: hexColors.light.primaryLight,
    lightPrimaryGlow: hexColors.light.primaryGlow,
    lightNeutral: hexColors.light.neutral,
    lightNeutralLight: hexColors.light.neutralLight,
    lightBackground: hexColors.light.background,
    lightSurface: hexColors.light.surface,
    lightCardBackground: hexColors.light.cardBackground,
    lightText: hexColors.light.text,
    lightTextSecondary: hexColors.light.textSecondary,
    lightTextMuted: hexColors.light.textMuted,
    lightBorder: hexColors.light.border,
    lightBorderGlow: hexColors.light.borderGlow,
    lightAccent: hexColors.light.accent,
    lightAccentLight: hexColors.light.accentLight,
    lightAccentGlow: hexColors.light.accentGlow,
    // Light neon colors
    lightNeonCyan: hexColors.light.neonCyan,
    lightNeonOrange: hexColors.light.neonOrange,
    lightNeonMagenta: hexColors.light.neonMagenta,
    lightNeonGreen: hexColors.light.neonGreen,
    lightNeonPurple: hexColors.light.neonPurple,
    lightNeonYellow: hexColors.light.neonYellow,
    lightNeonRed: hexColors.light.neonRed,
    lightSuccess: hexColors.light.success,
    lightError: hexColors.light.error,
    lightWarning: hexColors.light.warning,

    // Dark theme colors
    darkPrimary: hexColors.dark.primary,
    darkPrimaryLight: hexColors.dark.primaryLight,
    darkPrimaryGlow: hexColors.dark.primaryGlow,
    darkNeutral: hexColors.dark.neutral,
    darkNeutralLight: hexColors.dark.neutralLight,
    darkBackground: hexColors.dark.background,
    darkSurface: hexColors.dark.surface,
    darkCardBackground: hexColors.dark.cardBackground,
    darkText: hexColors.dark.text,
    darkTextSecondary: hexColors.dark.textSecondary,
    darkTextMuted: hexColors.dark.textMuted,
    darkBorder: hexColors.dark.border,
    darkBorderGlow: hexColors.dark.borderGlow,
    darkAccent: hexColors.dark.accent,
    darkAccentLight: hexColors.dark.accentLight,
    darkAccentGlow: hexColors.dark.accentGlow,
    // Dark neon colors
    darkNeonCyan: hexColors.dark.neonCyan,
    darkNeonOrange: hexColors.dark.neonOrange,
    darkNeonMagenta: hexColors.dark.neonMagenta,
    darkNeonGreen: hexColors.dark.neonGreen,
    darkNeonPurple: hexColors.dark.neonPurple,
    darkNeonYellow: hexColors.dark.neonYellow,
    darkNeonRed: hexColors.dark.neonRed,
    darkSuccess: hexColors.dark.success,
    darkError: hexColors.dark.error,
    darkWarning: hexColors.dark.warning,

    // Design system specific colors
    primary: hexColors.light.primary,
    neutral: hexColors.light.neutral,
  },
  space: {
    xs: spacing.phone.xs,
    sm: spacing.phone.sm,
    md: spacing.phone.md,
    lg: spacing.phone.lg,
    xl: spacing.phone.xl,
    xxl: spacing.phone.xxl,
  },
  size: {
    // Numeric tokens matching the spacing scale
    1: spacing.phone.xs,
    2: spacing.phone.sm,
    3: spacing.phone.md,
    4: spacing.phone.lg,
    5: spacing.phone.xl,
    6: spacing.phone.xxl,
    7: media.phone.buttonHeight,
    8: media.phone.topicCardSize,
    9: media.phone.colorSwatchSize,
    // Semantic tokens for specific use cases
    buttonHeight: media.phone.buttonHeight,
    topicCard: media.phone.topicCardSize,
    colorSwatch: media.phone.colorSwatchSize,
  },
  radius: {
    sm: radius.phone.sm,
    md: radius.phone.md,
    lg: radius.phone.lg,
    xl: radius.phone.xl,
    full: radius.phone.full,
  },
  fontSize: {
    // Numeric tokens (for Tamagui components)
    1: 13,
    2: 15,
    3: 17,
    4: 19,
    5: 22,
    6: 26,
    7: 30,
    8: 34,
    // Named tokens (default to phone sizes - use useResponsive() hook for device-specific sizes)
    tiny: typography.phone.fontSize.tiny,
    caption: typography.phone.fontSize.caption,
    label: typography.phone.fontSize.label,
    body: typography.phone.fontSize.body,
    title: typography.phone.fontSize.title,
    headline: typography.phone.fontSize.headline,
    display: typography.phone.fontSize.display,
    hero: typography.phone.fontSize.hero,
    // Tablet-specific sizes
    tinyTablet: typography.tablet.fontSize.tiny,
    captionTablet: typography.tablet.fontSize.caption,
    labelTablet: typography.tablet.fontSize.label,
    bodyTablet: typography.tablet.fontSize.body,
    titleTablet: typography.tablet.fontSize.title,
    headlineTablet: typography.tablet.fontSize.headline,
    displayTablet: typography.tablet.fontSize.display,
    heroTablet: typography.tablet.fontSize.hero,
  },
  zIndex: {
    0: 0,
    1: 1,
    2: 2,
    3: 3,
    4: 4,
    5: 5,
  },
});

const lightTheme = {
  primary: hexColors.light.primary,
  primaryLight: hexColors.light.primaryLight,
  primaryGlow: hexColors.light.primaryGlow,
  neutral: hexColors.light.neutral,
  neutralLight: hexColors.light.neutralLight,
  background: hexColors.light.background,
  surface: hexColors.light.surface,
  cardBackground: hexColors.light.cardBackground,
  text: hexColors.light.text,
  textSecondary: hexColors.light.textSecondary,
  textMuted: hexColors.light.textMuted,
  border: hexColors.light.border,
  borderGlow: hexColors.light.borderGlow,
  accent: hexColors.light.accent,
  accentLight: hexColors.light.accentLight,
  accentGlow: hexColors.light.accentGlow,
  // Neon colors
  neonCyan: hexColors.light.neonCyan,
  neonOrange: hexColors.light.neonOrange,
  neonMagenta: hexColors.light.neonMagenta,
  neonGreen: hexColors.light.neonGreen,
  neonPurple: hexColors.light.neonPurple,
  neonYellow: hexColors.light.neonYellow,
  neonRed: hexColors.light.neonRed,
  // Semantic
  success: hexColors.light.success,
  error: hexColors.light.error,
  warning: hexColors.light.warning,
};

const darkTheme = {
  primary: hexColors.dark.primary,
  primaryLight: hexColors.dark.primaryLight,
  primaryGlow: hexColors.dark.primaryGlow,
  neutral: hexColors.dark.neutral,
  neutralLight: hexColors.dark.neutralLight,
  background: hexColors.dark.background,
  surface: hexColors.dark.surface,
  cardBackground: hexColors.dark.cardBackground,
  text: hexColors.dark.text,
  textSecondary: hexColors.dark.textSecondary,
  textMuted: hexColors.dark.textMuted,
  border: hexColors.dark.border,
  borderGlow: hexColors.dark.borderGlow,
  accent: hexColors.dark.accent,
  accentLight: hexColors.dark.accentLight,
  accentGlow: hexColors.dark.accentGlow,
  // Neon colors
  neonCyan: hexColors.dark.neonCyan,
  neonOrange: hexColors.dark.neonOrange,
  neonMagenta: hexColors.dark.neonMagenta,
  neonGreen: hexColors.dark.neonGreen,
  neonPurple: hexColors.dark.neonPurple,
  neonYellow: hexColors.dark.neonYellow,
  neonRed: hexColors.dark.neonRed,
  // Semantic
  success: hexColors.dark.success,
  error: hexColors.dark.error,
  warning: hexColors.dark.warning,
};

export const config = createTamagui({
  tokens: tamaguiTokens,
  themes: {
    light: lightTheme,
    dark: darkTheme,
  },
  media: {
    xs: { maxWidth: 660 },
    sm: { maxWidth: 800 },
    md: { maxWidth: 1020 },
    lg: { maxWidth: 1280 },
    xl: { maxWidth: 1420 },
    xxl: { maxWidth: 1600 },
    gtXs: { minWidth: 660 + 1 },
    gtSm: { minWidth: 800 + 1 },
    gtMd: { minWidth: 1020 + 1 },
    gtLg: { minWidth: 1280 + 1 },
    short: { maxHeight: 820 },
    tall: { minHeight: 820 },
    hoverNone: { hover: 'none' },
    pointerCoarse: { pointer: 'coarse' },
  },
  shorthands: {
    px: 'paddingHorizontal',
    py: 'paddingVertical',
    bc: 'backgroundColor',
    br: 'borderRadius',
    bw: 'borderWidth',
    col: 'color',
    f: 'flex',
    m: 'margin',
    w: 'width',
    h: 'height',
  } as const,
});

export type AppConfig = typeof config;

declare module '@tamagui/core' {
  interface TamaguiCustomConfig extends AppConfig {}
}
