import { createTamagui, createTokens } from "@tamagui/core";
import { tokens } from "./tokens";
import { typography } from "../utils/responsive";

const tamaguiTokens = createTokens({
  color: {
    // Light theme colors
    lightPrimary: tokens.color.light.primary,
    lightPrimaryLight: tokens.color.light.primaryLight,
    lightPrimaryGlow: tokens.color.light.primaryGlow,
    lightNeutral: tokens.color.light.neutral,
    lightNeutralLight: tokens.color.light.neutralLight,
    lightBackground: tokens.color.light.background,
    lightSurface: tokens.color.light.surface,
    lightCardBackground: tokens.color.light.cardBackground,
    lightText: tokens.color.light.text,
    lightTextSecondary: tokens.color.light.textSecondary,
    lightTextMuted: tokens.color.light.textMuted,
    lightBorder: tokens.color.light.border,
    lightBorderGlow: tokens.color.light.borderGlow,
    lightAccent: tokens.color.light.accent,
    lightAccentLight: tokens.color.light.accentLight,
    lightAccentGlow: tokens.color.light.accentGlow,
    // Light neon colors
    lightNeonCyan: tokens.color.light.neonCyan,
    lightNeonOrange: tokens.color.light.neonOrange,
    lightNeonMagenta: tokens.color.light.neonMagenta,
    lightNeonGreen: tokens.color.light.neonGreen,
    lightNeonPurple: tokens.color.light.neonPurple,
    lightNeonYellow: tokens.color.light.neonYellow,
    lightNeonRed: tokens.color.light.neonRed,
    lightSuccess: tokens.color.light.success,
    lightError: tokens.color.light.error,
    lightWarning: tokens.color.light.warning,

    // Dark theme colors
    darkPrimary: tokens.color.dark.primary,
    darkPrimaryLight: tokens.color.dark.primaryLight,
    darkPrimaryGlow: tokens.color.dark.primaryGlow,
    darkNeutral: tokens.color.dark.neutral,
    darkNeutralLight: tokens.color.dark.neutralLight,
    darkBackground: tokens.color.dark.background,
    darkSurface: tokens.color.dark.surface,
    darkCardBackground: tokens.color.dark.cardBackground,
    darkText: tokens.color.dark.text,
    darkTextSecondary: tokens.color.dark.textSecondary,
    darkTextMuted: tokens.color.dark.textMuted,
    darkBorder: tokens.color.dark.border,
    darkBorderGlow: tokens.color.dark.borderGlow,
    darkAccent: tokens.color.dark.accent,
    darkAccentLight: tokens.color.dark.accentLight,
    darkAccentGlow: tokens.color.dark.accentGlow,
    // Dark neon colors
    darkNeonCyan: tokens.color.dark.neonCyan,
    darkNeonOrange: tokens.color.dark.neonOrange,
    darkNeonMagenta: tokens.color.dark.neonMagenta,
    darkNeonGreen: tokens.color.dark.neonGreen,
    darkNeonPurple: tokens.color.dark.neonPurple,
    darkNeonYellow: tokens.color.dark.neonYellow,
    darkNeonRed: tokens.color.dark.neonRed,
    darkSuccess: tokens.color.dark.success,
    darkError: tokens.color.dark.error,
    darkWarning: tokens.color.dark.warning,

    // Design system specific colors
    primary: tokens.color.light.primary,
    neutral: tokens.color.light.neutral,
  },
  space: {
    xs: tokens.space.xs,
    sm: tokens.space.sm,
    md: tokens.space.md,
    lg: tokens.space.lg,
    xl: tokens.space.xl,
    xxl: tokens.space.xxl,
  },
  size: {
    // Numeric tokens matching the spacing scale
    1: tokens.space.xs,
    2: tokens.space.sm,
    3: tokens.space.md,
    4: tokens.space.lg,
    5: tokens.space.xl,
    6: tokens.space.xxl,
    7: tokens.size.buttonHeight,
    8: tokens.size.topicCardSize,
    9: tokens.size.colorSwatchSize,
    10: tokens.size.toggleSize,
    // Semantic tokens for specific use cases
    buttonHeight: tokens.size.buttonHeight,
    topicCard: tokens.size.topicCardSize,
    colorSwatch: tokens.size.colorSwatchSize,
    toggle: tokens.size.toggleSize,
  },
  radius: {
    sm: tokens.radius.sm,
    md: tokens.radius.md,
    lg: tokens.radius.lg,
    xl: tokens.radius.xl,
    full: tokens.radius.full,
  },
  fontSize: {
    // Numeric tokens
    1: tokens.fontSize[1],
    2: tokens.fontSize[2],
    3: tokens.fontSize[3],
    4: tokens.fontSize[4],
    5: tokens.fontSize[5],
    6: tokens.fontSize[6],
    7: tokens.fontSize[7],
    8: tokens.fontSize[8],
    // Named tokens (default to phone sizes - use useResponsive() hook for device-specific sizes)
    h1: typography.phone.fontSize.h1,
    h2: typography.phone.fontSize.h2,
    body: typography.phone.fontSize.body,
    label: typography.phone.fontSize.label,
    small: typography.phone.fontSize.small,
    // Tablet-specific sizes
    h1Tablet: typography.tablet.fontSize.h1,
    h2Tablet: typography.tablet.fontSize.h2,
    bodyTablet: typography.tablet.fontSize.body,
    labelTablet: typography.tablet.fontSize.label,
    smallTablet: typography.tablet.fontSize.small,
  },
  zIndex: {
    0: 0,
    1: 1,
    2: 2,
    3: 3,
    4: 4,
    5: 5,
  },
});

const lightTheme = {
  primary: tokens.color.light.primary,
  primaryLight: tokens.color.light.primaryLight,
  primaryGlow: tokens.color.light.primaryGlow,
  neutral: tokens.color.light.neutral,
  neutralLight: tokens.color.light.neutralLight,
  background: tokens.color.light.background,
  surface: tokens.color.light.surface,
  cardBackground: tokens.color.light.cardBackground,
  text: tokens.color.light.text,
  textSecondary: tokens.color.light.textSecondary,
  textMuted: tokens.color.light.textMuted,
  border: tokens.color.light.border,
  borderGlow: tokens.color.light.borderGlow,
  accent: tokens.color.light.accent,
  accentLight: tokens.color.light.accentLight,
  accentGlow: tokens.color.light.accentGlow,
  // Neon colors
  neonCyan: tokens.color.light.neonCyan,
  neonOrange: tokens.color.light.neonOrange,
  neonMagenta: tokens.color.light.neonMagenta,
  neonGreen: tokens.color.light.neonGreen,
  neonPurple: tokens.color.light.neonPurple,
  neonYellow: tokens.color.light.neonYellow,
  neonRed: tokens.color.light.neonRed,
  // Semantic
  success: tokens.color.light.success,
  error: tokens.color.light.error,
  warning: tokens.color.light.warning,
};

const darkTheme = {
  primary: tokens.color.dark.primary,
  primaryLight: tokens.color.dark.primaryLight,
  primaryGlow: tokens.color.dark.primaryGlow,
  neutral: tokens.color.dark.neutral,
  neutralLight: tokens.color.dark.neutralLight,
  background: tokens.color.dark.background,
  surface: tokens.color.dark.surface,
  cardBackground: tokens.color.dark.cardBackground,
  text: tokens.color.dark.text,
  textSecondary: tokens.color.dark.textSecondary,
  textMuted: tokens.color.dark.textMuted,
  border: tokens.color.dark.border,
  borderGlow: tokens.color.dark.borderGlow,
  accent: tokens.color.dark.accent,
  accentLight: tokens.color.dark.accentLight,
  accentGlow: tokens.color.dark.accentGlow,
  // Neon colors
  neonCyan: tokens.color.dark.neonCyan,
  neonOrange: tokens.color.dark.neonOrange,
  neonMagenta: tokens.color.dark.neonMagenta,
  neonGreen: tokens.color.dark.neonGreen,
  neonPurple: tokens.color.dark.neonPurple,
  neonYellow: tokens.color.dark.neonYellow,
  neonRed: tokens.color.dark.neonRed,
  // Semantic
  success: tokens.color.dark.success,
  error: tokens.color.dark.error,
  warning: tokens.color.dark.warning,
};

export const config = createTamagui({
  tokens: tamaguiTokens,
  themes: {
    light: lightTheme,
    dark: darkTheme,
  },
  media: {
    xs: { maxWidth: 660 },
    sm: { maxWidth: 800 },
    md: { maxWidth: 1020 },
    lg: { maxWidth: 1280 },
    xl: { maxWidth: 1420 },
    xxl: { maxWidth: 1600 },
    gtXs: { minWidth: 660 + 1 },
    gtSm: { minWidth: 800 + 1 },
    gtMd: { minWidth: 1020 + 1 },
    gtLg: { minWidth: 1280 + 1 },
    short: { maxHeight: 820 },
    tall: { minHeight: 820 },
    hoverNone: { hover: "none" },
    pointerCoarse: { pointer: "coarse" },
  },
  shorthands: {
    px: "paddingHorizontal",
    py: "paddingVertical",
    bc: "backgroundColor",
    br: "borderRadius",
    bw: "borderWidth",
    col: "color",
    f: "flex",
    m: "margin",
    w: "width",
    h: "height",
  } as const,
});

export type AppConfig = typeof config;

declare module "@tamagui/core" {
  interface TamaguiCustomConfig extends AppConfig {}
}
