import { avatarColor } from '../utils/colors';

import { AVATAR_ART } from './avatarArt';

/**
 * Curated avatar catalog — 36 Open Peeps characters vendored as SVG strings
 * (config/avatarArt.ts, generated by scripts/avatar-gen). The stored wire
 * value is the TOKEN, a MIRROR of AVATAR_TOKENS in the backend
 * (src/db/appUsers.ts). The server validates against its copy (values render
 * verbatim in other users' UIs, so it must never accept free text); keep the
 * two lists in sync. Additions are backward-safe, removals are not (existing
 * rows keep the value). Legacy emoji values already stored on the server
 * still render via AvatarDisc's text fallback.
 *
 * Each token also carries a SIGNATURE COLOR from the neon palette for the
 * gradient disc behind the art: choosing an avatar chooses a look, and that
 * look follows the user everywhere the disc renders (picker preview,
 * comments, leaderboard rows). The picker rail stacks the catalog into
 * columns of AVATAR_RAIL_ROWS; each column shares one hue, sweeping
 * red → magenta so the rail reads as a rainbow.
 */

/** Neon palette keys avatars may use — a subset of theme/hexColors. */
export type AvatarColorKey =
  'neonRed' | 'neonOrange' | 'neonYellow' | 'neonGreen' | 'neonCyan' | 'neonPurple' | 'neonMagenta';

export type AvatarToken = (typeof AVATAR_ART)[number]['token'];

/** Rows in the picker rail — also the column size the hue sweep is keyed to. */
export const AVATAR_RAIL_ROWS = 3;

const HUE_SWEEP: AvatarColorKey[] = [
  'neonRed',
  'neonOrange',
  'neonYellow',
  'neonGreen',
  'neonCyan',
  'neonPurple',
  'neonMagenta',
];

const columnCount = Math.ceil(AVATAR_ART.length / AVATAR_RAIL_ROWS);

export const AVATAR_CATALOG: { token: AvatarToken; xml: string; colorKey: AvatarColorKey }[] =
  AVATAR_ART.map((entry, index) => {
    const column = Math.floor(index / AVATAR_RAIL_ROWS);
    return {
      token: entry.token,
      xml: entry.xml as string,
      colorKey: HUE_SWEEP[Math.round((column * (HUE_SWEEP.length - 1)) / (columnCount - 1))],
    };
  });

export const AVATAR_TOKENS = AVATAR_CATALOG.map((entry) => entry.token);

const ART_BY_TOKEN = Object.fromEntries(
  AVATAR_CATALOG.map((entry) => [entry.token, entry.xml])
) as Record<AvatarToken, string>;

const COLOR_BY_TOKEN = Object.fromEntries(
  AVATAR_CATALOG.map((entry) => [entry.token, entry.colorKey])
) as Record<AvatarToken, AvatarColorKey>;

/** The pre-rendered SVG for a stored avatar value, or undefined when the
 * value is absent or not a known token (legacy emoji rows). */
export function avatarXmlFor(value: string | null | undefined): string | undefined {
  return value ? ART_BY_TOKEN[value as AvatarToken] : undefined;
}

/** The signature hex for a stored avatar value, or undefined when the value
 * is absent or not a known token. */
export function avatarSignatureColor(
  value: string | null | undefined,
  palette: Record<AvatarColorKey, string>
): string | undefined {
  const key = value ? COLOR_BY_TOKEN[value as AvatarToken] : undefined;
  return key ? palette[key] : undefined;
}

/**
 * The identity accent for a user's disc wherever it renders: the avatar's
 * signature color when they've picked one from the catalog, otherwise the
 * stable name-hash color (legacy emoji rows and users with no avatar look
 * exactly as they always did).
 */
export function identityColor(
  name: string,
  avatar: string | null | undefined,
  palette: Record<AvatarColorKey, string>
): string {
  return avatarSignatureColor(avatar, palette) ?? avatarColor(name, palette);
}
